# Generated by Django 4.2.2 on 2023-07-23 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0004_answer_modify_date_question_modify_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='auth',
            new_name='author',
        ),
    ]
